Pizza myPizza =new Pizza('M',2,3);



System.debug ('Your ' + myPizza.size + '  size pizza with ' + myPizza.numberOfCheeseTopping +
 ' numberOfCheeseTopping and ' + myPizza.numberOfPepperoniTopping +
 ' numberOfPepperoniTopping costs: $ ' +  myPizza.calcCost() ); 

//Your M size pizza with 2 numberOfCheeseTopping and 3 numberOfPepperoniTopping costs $20.

 Pizza yourPizza = new Pizza ();

 System.debug(yourPizza); 
