/*1. Create a variable contains your full name
   - print it out in uppercase
   - print it out in lowercase
   - find the index of space and print
   - print first char of first and last name together :initials*/


String fullName = 'Cavidan Mercan' ;

System.debug( fullName.toUpperCase()); 

System.debug( fullName.toLowerCase()); 

System.debug( fullName.indexOf(' ')); 

System.debug(fullName.left(1)+fullName.mid(8,1)); 






